---
- name: Setup Web server
  hosts: localhost
  become: yes
  become_user: root

  tasks:
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install fontconfig
    shell: apt install fontconfig -y    

  - name: Install java
    shell: apt install fontconfig openjdk-17-jre -y  

  - name: Checking java version
    shell: java -version  
   
  - name: Install Nginx
    apt: name=nginx state=latest

    notify:
      - restart nginx

  handlers:
  - name: restart nginx
    service: name=nginx state=reloaded
